@echo off
call remove_nuspec_ro.cmd
nuver /a:%1 /path:BreviteeToolkit\BreviteeToolkit.nuspec
nuver /a:%1 /path:Brevitee\Brevitee.nuspec 
nuver /a:%1 /path:Brevitee.Analytics\Brevitee.Analytics.nuspec
nuver /a:%1 /path:Brevitee.Automation\Brevitee.Automation.nuspec
nuver /a:%1 /path:Brevitee.CommandLine\Brevitee.CommandLine.nuspec 
nuver /a:%1 /path:Brevitee.Data\Brevitee.Data.nuspec
nuver /a:%1 /path:Brevitee.Data.Repositories\Brevitee.Data.Repositories.nuspec
nuver /a:%1 /path:Brevitee.Distributed\Brevitee.Distributed.nuspec
nuver /a:%1 /path:Brevitee.Drawing\Brevitee.Drawing.nuspec
nuver /a:%1 /path:Brevitee.Dust\Brevitee.Dust.nuspec
nuver /a:%1 /path:Brevitee.Encryption\Brevitee.Encryption.nuspec
nuver /a:%1 /path:Brevitee.Html\Brevitee.Html.nuspec
nuver /a:%1 /path:Brevitee.Incubation\Brevitee.Incubation.nuspec 
nuver /a:%1 /path:Brevitee.Javascript\Brevitee.Javascript.nuspec
nuver /a:%1 /path:Brevitee.Logging\Brevitee.Logging.nuspec 
nuver /a:%1 /path:Brevitee.Management\Brevitee.Management.nuspec
nuver /a:%1 /path:Brevitee.Messaging\Brevitee.Messaging.nuspec
nuver /a:%1 /path:Brevitee.Net\Brevitee.Net.nuspec
nuver /a:%1 /path:Brevitee.Profiguration\Brevitee.Profiguration.nuspec
nuver /a:%1 /path:Brevitee.Schema.Org\Brevitee.Schema.Org.nuspec
nuver /a:%1 /path:Brevitee.Server\Brevitee.Server.nuspec 
nuver /a:%1 /path:Brevitee.ServiceProxy\Brevitee.ServiceProxy.nuspec 
nuver /a:%1 /path:Brevitee.SourceControl\Brevitee.SourceControl.nuspec 
nuver /a:%1 /path:Brevitee.Syndication\Brevitee.Syndication.nuspec 
nuver /a:%1 /path:Brevitee.Testing\Brevitee.Testing.nuspec 
nuver /a:%1 /path:Brevitee.UserAccounts\Brevitee.UserAccounts.nuspec
nuver /a:%1 /path:Brevitee.Yaml\Brevitee.Yaml.nuspec